2kms tdb aws gcs ossl3
OmicsDataAutomation/TileDB pull request #143
Opened 2023-03-13 05:26 UTC by Santhosh-K-M

2023-03-13 16:18 UTC, nalinigans commented on cmake/patches/gcssdk/gcs_ossl.patch
> ++    md5_digest = (unsigned char*)OPENSSL_malloc(md5_digest_len);
Memory leak, OPENSSL_malloc() is just a malloc wrapper, it should have a matching OPENSSL_free() function. Read [man pages.](https://www.openssl.org/docs/man1.1.1/man3/OPENSSL_malloc.html)

2023-03-13 16:18 UTC, nalinigans commented on cmake/patches/gcssdk/gcs_ossl.patch
> ++    md5_digest = (unsigned char*)OPENSSL_malloc(md5_digest_len);
memory leak with memory from OPENSSL_malloc() not being freed.

2023-03-13 16:18 UTC, nalinigans commented on core/include/codec/codec.h
> -  /* ********************************* */
Please leave the dynamic loading support in codec.h as we are not using it with openssl. We could move it later to common utils with another PR.

2023-03-13 16:18 UTC, nalinigans commented on core/src/storage_manager/storage_s3.cc
> +  ossl_shim_init();
No need to call ossl_shim_init.

2023-03-13 16:18 UTC, nalinigans commented on test/src/codec/test_codec.cc
>  #include "codec.h"
Please revert `test_codec.cc` as we are not using dynamic loading for openssl3 support.

2023-03-13 16:36 UTC, nalinigans commented
The OpenSSL3 codepaths have not been tested with Github workflows - see https://github.com/OmicsDataAutomation/TileDB/blob/a6f4a866ed5b796269ed4f49ea8288a8b4cf5129/.github/workflows/basic.yml#L118. and https://github.com/OmicsDataAutomation/TileDB/blob/a6f4a866ed5b796269ed4f49ea8288a8b4cf5129/.github/workflows/basic.yml#L144. Please add additional builds and/or steps to test openssl3 support for Ubuntu 22.04 and MacOS.

2023-03-16 19:27 UTC, nalinigans requested changes
Would it be possible to turn on the gcs and azure tests for ubuntu 22.04 with openssl 3 too? On another note, we probably can use this same `tiledb_openssl_shim.h` with `https://github.com/OmicsDataAutomation/azure-storage-cpplite` too. Would you be able to work on that in parallel?

2023-03-17 23:50 UTC, mlathara commented on cmake/patches/gcssdk/gcs_ossl.patch
> ++      md5_digest_len = EVP_MD_size(EVP_sha1());
It seems like we can't get to the above line given that the else condition guarantees version > 3

2023-03-17 23:51 UTC, mlathara commented on cmake/patches/gcssdk/gcs_ossl.patch
> ++      md5_digest_len = EVP_MD_size(EVP_sha1());
Should be possible to get to the above line, right?

2023-03-17 23:52 UTC, mlathara commented on cmake/patches/gcssdk/gcs_ossl.patch
> ++      md5_digest_len = EVP_MD_size(EVP_sha1());
Shouldn't be possible to get to the above line, right?

2023-03-17 23:54 UTC, mlathara commented on cmake/patches/awssdk/aws_ossl.patch
> ++// #include <openssl/md5.h>
nit: There's a few instances of commented out lines in this patch (like above) which you could remove

2023-03-17 23:55 UTC, mlathara reviewed
Mostly looks good - just some minor comments. Good job getting those tests to pass.

2023-03-18 17:23 UTC, nalinigans commented on core/src/c_api/tiledb_utils.cc
> +#include "tiledb_openssl_shim.h"
tiledb_openssl_shim.h has been included, but there seem to be no openssl3 related changes in this file. Why?

2023-03-18 17:23 UTC, nalinigans commented on core/src/metadata/metadata.cc
> +#include "tiledb_openssl_shim.h"
tiledb_openssl_shim.h has been included, but there seem to be no openssl3 related changes in this file. Why?

2023-03-18 17:36 UTC, Santhosh-K-M commented on core/src/c_api/tiledb_utils.cc
> +#include "tiledb_openssl_shim.h"
At line number 330, we are calling a function called MD5(), which is defined as weak attribute in tiledb_openssl_shim.h

2023-03-18 17:37 UTC, Santhosh-K-M commented on core/src/metadata/metadata.cc
> +#include "tiledb_openssl_shim.h"
Here also we are calling MD5() function at line 104 & 417, so we need tiledb_openssl_shim.h file

2023-03-18 21:05 UTC, mlathara approved these changes
looks good to me

2023-03-19 00:52 UTC, nalinigans commented on core/src/c_api/tiledb_utils.cc
> +#include "tiledb_openssl_shim.h"
If you are not changing anything, why not leave #include <openssl/md5.h> as is. If keeping it as is putting out deprecated warnings with openssl3, you will have to have implement the alternate md5 methods for openssl3 as you have done for aws and s3 to use tiledb_openssl_shim.h. Does that make sense?

2023-03-19 00:53 UTC, nalinigans commented on core/src/metadata/metadata.cc
> +#include "tiledb_openssl_shim.h"
Same as my previous comment above. Sorry for the nitpicking,

2023-03-19 08:30 UTC, Santhosh-K-M commented on core/src/c_api/tiledb_utils.cc
> +#include "tiledb_openssl_shim.h"
I tried using the old file and getting the warnings like below.
So defined it as weak attribute in tiledb_openssl_shim.h & included it.

/nfs/home/santhosh/workbenchKms/2tdb_ossl3_aws_gcs/TileDB/core/src/c_api/tiledb_utils.cc: In function ‘void TileDBUtils::print_md5_hash(unsigned char*, size_t)’:
/nfs/home/santhosh/workbenchKms/2tdb_ossl3_aws_gcs/TileDB/core/src/c_api/tiledb_utils.cc:331:6: warning: ‘unsigned char* TileDBUtils::MD5(const unsigned char*, size_t, unsigned char*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
  331 |   MD5(buffer, length, md);
      |   ~~~^~~~~~~~~~~~~~~~~~~~
In file included from /nfs/home/santhosh/workbenchKms/2tdb_ossl3_aws_gcs/TileDB/core/src/c_api/tiledb_utils.cc:328:
/usr/include/openssl/md5.h:52:38: note: declared here
   52 | OSSL_DEPRECATEDIN_3_0 unsigned char *MD5(const unsigned char *d, size_t n,
      |                                      ^~~

2023-03-19 08:31 UTC, Santhosh-K-M commented on core/src/metadata/metadata.cc
> +#include "tiledb_openssl_shim.h"
Here I get the error as:
/nfs/home/santhosh/workbenchKms/2tdb_ossl3_aws_gcs/TileDB/core/src/metadata/metadata.cc: In member function ‘int Metadata::read(const char*, void**, size_t*)’:
/nfs/home/santhosh/workbenchKms/2tdb_ossl3_aws_gcs/TileDB/core/src/metadata/metadata.cc:102:3: error: ‘MD5’ was not declared in this scope
  102 |   MD5((const unsigned char*) key, strlen(key)+1, (unsigned char*) coords);
      |   ^~~
/nfs/home/santhosh/workbenchKms/2tdb_ossl3_aws_gcs/TileDB/core/src/metadata/metadata.cc: In member function ‘void Metadata::compute_array_coords(const char*, size_t, void*&, size_t&) const’:
/nfs/home/santhosh/workbenchKms/2tdb_ossl3_aws_gcs/TileDB/core/src/metadata/metadata.cc:415:5: error: ‘MD5’ was not declared in this scope
  415 |     MD5(keys_c, key_size, coords_c);
      |     ^~~
make[2]: *** [core/CMakeFiles/TILEDB_CORE_OBJECTS.dir/build.make:412: core/CMakeFiles/TILEDB_CORE_OBJECTS.dir/src/metadata/metadata.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:571: core/CMakeFiles/TILEDB_CORE_OBJECTS.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

2023-03-20 17:22 UTC, nalinigans commented on core/src/metadata/metadata.cc
> +#include "tiledb_openssl_shim.h"
One of the aims of this exercise was to not just suppress deprecation warnings but to start using the openssl3 functionality instead of openssl1. Using `tiledb_openssl_shim` only suppresses the error, we should also be using the appropriate MD5 api from openssl3. See https://www.openssl.org/docs/man3.1/man3/MD5.html for what should be used for replacements.

2023-03-20 17:22 UTC, nalinigans commented on core/src/c_api/tiledb_utils.cc
> +#include "tiledb_openssl_shim.h"
One of the aims of this exercise was to not just suppress deprecation warnings but to start using the openssl3 functionality instead of openssl1. Using `tiledb_openssl_shim` only suppresses the error, we should also be using the appropriate MD5 api from openssl3. See https://www.openssl.org/docs/man3.1/man3/MD5.html for what should be used for replacements.

2023-04-21 17:14 UTC, closed without merging