Changed query string to vector
OmicsDataAutomation/TileDB pull request #151
Opened 2023-06-21 17:39 UTC by eneskuluk

Changes variable query_ from string vector that consists of pairs.

2023-06-21 17:41 UTC, eneskuluk commented on test/src/misc/test_uri.cc
> +  test_uri("hdfs://oda-master:9000/tmp", "hdfs", "oda-master", 9000, "/tmp", std::vector<std::pair<std::string, std::string>>());
should i change the empty vectors to a single variable that is reused in the empty queries? like `std::vector<std::pair<std::string, std::string>> emptyVector` and use this in empty queries instead of using seperate vectors each time?

2023-06-21 17:45 UTC, eneskuluk commented on core/src/misc/uri.cc
> +        //throw std::system_error(EINVAL, std::generic_category(), "Query doesn't have value or not in proper format");
Should we throw error and terminate if query includes errors? currently it continues to parse even if it includes errors, it just skips to next parameter. Like following query 
`?query&anotherquery=someval&otherquery&` will result in vector having only one variable, key as anotherquery, value as someval with no errors. since initial and last 2 query parameters are missing/incorrect.

2023-06-21 17:47 UTC, eneskuluk commented on core/src/misc/uri.cc
> +    handle edge cases later
there could be edge cases i forgot to include, tried to include that I could think of at that moment, will try to update If i think/encounter new ones.

2023-06-21 17:51 UTC, eneskuluk commented on core/include/misc/uri.h
> +  std::vector<std::pair<std::string, std::string>> query_;
Initially thought about using unordered set since retrieval would be faster If we are going to search keys when processing query, but since the size of the vector going to be very small, I think it is negligible right?

2023-06-21 18:13 UTC, nalinigans commented on core/include/misc/uri.h
> +  std::vector<std::pair<std::string, std::string>> query_;
Actually using a set is a good idea as the code will be a lot cleaner for searching by keys.

2023-06-21 19:40 UTC, nalinigans commented on core/include/misc/uri.h
> +  std::vector<std::pair<std::string, std::string>> query_;
Does not matter, unordered set or map is great. Would it be possible to change to `unordered map`?

2023-06-21 19:45 UTC, eneskuluk commented on core/include/misc/uri.h
> +  std::vector<std::pair<std::string, std::string>> query_;
Sure, I already changed it. It is currently in the checks

2023-06-21 19:59 UTC, nalinigans commented on core/src/misc/uri.cc
> +        //throw std::system_error(EINVAL, std::generic_category(), "Query doesn't have value or not in proper format");
Yes, we need to throw exceptions for errors and catch the exception to return an error status(usually an integer of 0) in the caller.

2023-06-21 21:40 UTC, nalinigans requested changes
Please do add tests that throw exceptions in the query processing too. Thanks.

2023-06-21 21:40 UTC, nalinigans commented on core/src/misc/uri.cc
> +        //throw std::system_error(EINVAL, std::generic_category(), "Query doesn't have value or not in proper format");
Yes, we need to throw exceptions for errors. The exception should be handled by the caller.

2023-06-21 21:40 UTC, nalinigans commented on core/src/misc/uri.cc
> +    handle edge cases later
See if you can create unit tests that would be edge cases.

2023-06-21 21:40 UTC, nalinigans commented on test/src/misc/test_uri.cc
> +  CHECK(path_uri.query().empty() == query.empty());
Should'nt this line be `if query.empty() CHECK(path_uri.query().empty() == query.empty());`

2023-06-21 21:40 UTC, nalinigans commented on test/src/misc/test_uri.cc
> +  CHECK(path_uri.query().empty() == query.empty());
Also, you can add these lines 
```
if (!query.empty()) {
  CHECK(path_uri.query.length() == query.length);
  for(auto pair: query){
     CHECK(path_uri.query().find(pair.first) != path_uri.query().end());
     CHECK_THAT(pair.second, Equals(path_uri.query()[pair.first]));
   }
}
```

2023-06-21 22:13 UTC, eneskuluk commented on core/src/misc/uri.cc
> +        //throw std::system_error(EINVAL, std::generic_category(), "Query doesn't have value or not in proper format");
Is following enough: ` throw std::system_error(EINVAL, std::generic_category(), "Query is in incorrect format");`
What do you mean by caller? 
On testing side I did `REQUIRE_THROWS(test_uri("fdfdfd://dfdfd/fdfdf?firstQ=firstval&secondQ", "fdfdfd", "dfdfd", 0, "/fdfdf",emptyMap));`
Is this the correct way to do it?

2023-06-21 22:15 UTC, eneskuluk commented on core/src/misc/uri.cc
> +        //throw std::system_error(EINVAL, std::generic_category(), "Query doesn't have value or not in proper format");
query above should fail in the code right? currently it is skipping improperly formatted part picking correctly formatted parts. if a part of the query fails, should we end it completely?

2023-06-21 22:29 UTC, nalinigans commented on core/src/misc/uri.cc
> +        //throw std::system_error(EINVAL, std::generic_category(), "Query doesn't have value or not in proper format");
Caller in this context is the method calling/using the URI functionality. But, yes, this change with the testing side is enough.

2023-06-21 22:32 UTC, eneskuluk commented on test/src/misc/test_uri.cc
> +  CHECK(path_uri.query().empty() == query.empty());
I think it is better to check even if query is empty since path_uri's map could be not empty. So checking their lengths could be good to catch it. If query is empty, it won't go into the for loop anyway. Does the following looks good to you:
```
CHECK(path_uri.query.length() == query.length);
for(auto pair: query){
   CHECK(path_uri.query().find(pair.first) != path_uri.query().end());
   CHECK_THAT(pair.second, Equals(path_uri.query()[pair.first]));
 }
```

2023-06-22 22:10 UTC, nalinigans requested changes
Just wondering if you could format the new code roughly with [Google Style](https://google.github.io/styleguide/cppguide.html)? @webberlh tells me VSCode has hooks for setting up this stye for formatting C/C++ source.

2023-06-22 22:10 UTC, nalinigans commented on core/src/misc/uri.cc
> -    query_.assign(query_iter, end_iter);
Just wondering if you could make this code a little bit concise using the existing code? Something on the lines of the following -
```
  if (query_iter != end_iter) {
    ++query_iter;
    query_.assign(query_iter, end_iter);
    char *save_ptr = query_.data();
    while (query_token_pair = strtok_r(query_.data(), "&", &save_ptr)) {
      key_length = query_token_pair.find("=");
      std::cout << "key=" <<  query_token_pair.substr(0, key_length-2) << " value=" << query_token_pair.substr(key_length, query_token_pair.length()-1) << std::endl;
    }
  }
```

2023-06-22 22:10 UTC, nalinigans commented on core/src/misc/uri.cc
> +std::size_t startQuery = uri_s.find('?') + 1;
You are starting to parse from the beginning that is not necessary. You should continue from `path_iter` in the original code. See the example code I posted with the original code.

2023-06-23 03:02 UTC, webberlh commented
>  @webberlh tells me VSCode has hooks for setting up this stye for formatting C/C++ source.
Specifically, I use the [clang-format](https://marketplace.visualstudio.com/items?itemName=xaver.clang-format) extension which can hook into your native `clang-format` binary for doing the formatting.

2023-06-23 05:03 UTC, eneskuluk commented
> Just wondering if you could format the new code roughly with [Google Style](https://google.github.io/styleguide/cppguide.html)? @webberlh tells me VSCode has hooks for setting up this stye for formatting C/C++ source.

I now chose Google style formatting in cpp formatting in vs code settings. I'll format modified/added parts before committing. That should be enough for formatting wise right?

2023-06-23 05:10 UTC, eneskuluk commented on core/src/misc/uri.cc
> +std::size_t startQuery = uri_s.find('?') + 1;
I see that makes sense, but when I used path_iter, it was returning iterator but I planned my code to work on indexes so it wasn't usable in my case. It starts looking for `?` from beginning, didn't think that would be a performance concern since there wouldn't be much characters until question mark. I'll check the example code thanks, I'll try to fix it.

2023-06-23 07:47 UTC, eneskuluk commented on core/src/misc/uri.cc
> -    query_.assign(query_iter, end_iter);
Thanks for providing some sample code. I'll check if I can do it both readable and concise after handling the edge cases with following template.

2023-06-26 23:38 UTC, nalinigans approved these changes
LGTM

2023-06-27 01:46 UTC, mlathara commented on core/src/misc/uri.cc
> +      query_[key] = std::string(++search);
Do we need to decode from [url-encoded format](https://en.wikipedia.org/wiki/Query_string#URL_encoding) here?

2023-06-27 16:51 UTC, nalinigans commented on core/src/misc/uri.cc
> +      query_[key] = std::string(++search);
Not sure what you want done here, C++ is pretty agnostic to encodings, probably have to write our own decoders here. Also see [std::codecvt](https://en.cppreference.com/w/cpp/locale/codecvt) for some not so great support. My suggestion is to get the upstream components to pass already decoded uri strings to this layer.

2023-06-27 18:22 UTC, nalinigans commented on core/src/misc/uri.cc
> +      query_[key] = std::string(++search);
arrow uses `https://github.com/uriparser/uriparser` for parsing URIs

2023-06-27 20:44 UTC, mlathara approved these changes
lgtm

2023-06-27 22:10 UTC, merged