Add azb support
OmicsDataAutomation/TileDB pull request #154
Opened 2023-07-05 16:09 UTC by eneskuluk

Adds azb support with following format: azb://<container name>/<path>/<query>

2023-07-05 21:16 UTC, nalinigans requested changes
Can you please add `azb"//` tests to azurite? - see https://github.com/OmicsDataAutomation/TileDB/blob/18a85333507f26bc7702a7faab2cc1e672e53ebe/.github/scripts/run_dfs_tests.sh#L109. This also exercises the endpoint paths.

2023-07-05 21:16 UTC, nalinigans commented on core/include/storage_manager/storage_fs.h
> +    std::size_t query_pos = path.find('?');
At this point, in storage_fs.h, we should not be having `query parameters` and you should not have to check for `?` as they should only be `paths` being passed around. Where are you encountering this?

2023-07-05 21:16 UTC, nalinigans commented on test/src/c_api/test_tiledb_utils.cc
> +std::string append_helper(const std::string &temp_dir,
You should be able to move this `append_helper` to `test/include/catch2/catch.h` and use this helper routine with `append_slash` too. Probably also rename `append_helper` to just `append`.

2023-07-05 21:16 UTC, nalinigans commented on test/src/storage_manager/test_azure_blob_storage.cc
> +        std::string home_dir;
You can use the `append_helper` here too!

2023-07-11 23:01 UTC, nalinigans requested changes

2023-07-11 23:07 UTC, eneskuluk commented on .github/scripts/run_dfs_tests.sh
> +    $CMAKE_BUILD_DIR/test/test_azure_blob_storage --test-dir "azb://$AZURE_CONTAINER_NAME/$TEST?account=$AZURE_STORAGE_ACCOUNT" &&
was planning to add that to endpoint pr

2023-07-11 23:09 UTC, eneskuluk commented on test/include/catch2/catch.h
> +    if(path.find('?') == std::string::npos && path[path.size()]!='/') {
This is a leftover before the refactor I think, forgot to revert some of the changes.

2023-07-11 23:10 UTC, eneskuluk commented on test/include/catch2/catch.h
> +      }
I created append function before I changed here, I will fix this as well.

2023-07-11 23:22 UTC, nalinigans commented
@eneskuluk, can you please add the following copyright line in the license header to all the changed files? Thanks.
```
* @copyright Copyright (c) 2023 dātma, inc™
```

2023-07-11 23:25 UTC, eneskuluk commented on test/src/c_api/test_tiledb_utils.cc
> +const std::string& workspace("/WORKSPACE");
In every case workspace string being used, we are appending slash to it, why not adding at the beginning instead of adding at every step? Is there a reason for that?

2023-07-11 23:52 UTC, eneskuluk commented on test/include/catch2/catch.h
> +std::string append(const std::string &temp_dir, const std::string &append) {
In test_tiledb_utils where append is being used, sometimes it is not required to append slash, that's why I wasn't appending slash as default since I was expecting it to be a part of append since it will go behind the query part.

2023-07-12 00:33 UTC, nalinigans commented on .github/scripts/run_dfs_tests.sh
> +    $CMAKE_BUILD_DIR/test/test_azure_blob_storage --test-dir "azb://$AZURE_CONTAINER_NAME/$TEST?account=$AZURE_STORAGE_ACCOUNT" &&
Ah, ok, that's some then. Thanks.

2023-07-13 15:48 UTC, mlathara commented on core/src/c_api/tiledb_utils.cc
> +    return dir + "/" + path;
Do we need to worry about supporting the case where `dir` already ends in `slash`? For cloud paths, the extra slash will make a difference - they're not the same URI

2023-07-13 16:06 UTC, nalinigans commented on core/src/c_api/tiledb_utils.cc
> +    return dir + "/" + path;
Yes, we need to. That is what the `slashify` routines in other parts of the code do.

2023-07-14 17:46 UTC, nalinigans reviewed
Looks good mostly. Have requested minor changes. Thanks.

2023-07-14 17:46 UTC, nalinigans commented on core/include/storage_manager/storage_fs.h
> + * @copyright Copyright (c) 2023 dātma, inc™
No effective changes in storage_fs.h. Just revert this.

2023-07-14 17:46 UTC, nalinigans commented on core/src/c_api/tiledb_utils.cc
> +    return dir + "/" + path;
Can you use `slashify(dir)+path` instead of `dir + "/" + path`? See @mlathara's comment above.

2023-07-14 17:46 UTC, nalinigans commented on core/src/c_api/tiledb_utils.cc
> +    return dir.substr(0, query_pos) + ("/" + path) +
Same comment for line 86. Can you use `slashify(dir.substr(0, query_pos))`?

2023-07-14 17:46 UTC, nalinigans commented on test/include/catch2/catch.h
> +      }
You could improve upon this piece of code by using `slashify` as well.

2023-07-14 17:46 UTC, nalinigans commented on test/src/storage_manager/test_azure_blob_storage.cc
> +        azure_blob = new AzureBlob(append(temp_dir->get_temp_dir(), "/test_azure_blob"));
You should not have to use `/test_azure_blob` here. Just a `test_azure_blob` should suffice without the slash.

2023-07-14 20:12 UTC, nalinigans approved these changes

2023-07-21 00:32 UTC, merged